steps:
  - label: ":hammer: Tests"
    command: mvn compiler:compile
    agents:
        queue: "medium"

  - wait

  - label: ":package: Package"
    command: mvn package
    agents:
        queue: "medium"

  - wait

  - label: ":debian: Install"
    command: mvn install
    agents:
        queue: "medium"

