steps:
  - commands: mvn clean

  - label: ":hammer: Tests"
    commands: mvn compiler:compile
    agents:
        queue: medium

  - wait

  - label: ":package: Package"
    commands: mvn package
    agents:
        queue: medium

  - wait

  - label: ":debian: Publish"
    commands: mvn install
    agents:
        queue: medium

