steps:
  - label: ":hammer: Tests"
    command: mvn clean compile
    branches: "testing"
    agents:
        queue: "medium"

  - wait

  - label: ":package: Package"
    command: mvn package
    branches: "testing"
    agents:
        queue: "medium"

  - wait

  - label: ":debian: Install"
    command: mvn install
    branches: "testing"
    agents:
        queue: "medium"

