steps:
  - block: "Deploy"
    prompt: "Deploy to production?"
  - label: ":ecs: 🚀"
    concurrency: 1
    concurrency_group: "rails-app-deploy"
    plugins:
      - ecs-deploy#v1.3.0:
        cluster: "production"
        service: "app"
        task-definition: "production-deploy/sport-service"
        task-family: "rails-app"
        image: "746157492983.dkr.ecr.ap-southeast-1.amazonaws.com/scorz:sport-service-049dc24"
        task-role-arn: "deployer"
        deployment-configuration: "100/200"

      

