steps:

  - label: ":mvn: Installing Maven on agent"
    commands: apt install maven
    branches: "master"
    agents:
        queue: "medium"
        
  - label: ":hammer: Tests"
    commands: |
        echo "compiling code"      
        mvn clean compile
    branches: "master"
    agents:
        queue: "medium"

  - wait

  - label: ":package: Package"
    command: mvn package
    branches: "master"
    agents:
        queue: "medium"

  - wait

  - label: ":debian: Install"
    command: mvn install
    branches: "master"
    agents:
        queue: "medium"

