steps:
  - command: mvn clean

  - label: ":hammer: Tests"
    command: mvn compiler:compile
    agents:
        queue: "medium"

  - wait

  - label: ":package: Package"
    command: mvn package
    agents:
        queue: "medium"

  - wait

  - label: ":debian: Publish"
    command: mvn install
    agents:
        # We use a medium sized instance instead of the normal small ones because
        # gradle build is long
        queue: "medium"

